import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Navbar from "~/components/ui/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} flex justify-center bg-slate-800 text-white`}
      >
        <div className="w-full max-w-7xl ">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
